"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getDashboardStats = exports.deletePost = exports.deleteTrail = exports.updateTrail = exports.createTrail = exports.getTrail = exports.listTrails = exports.deleteMountain = exports.updateMountain = exports.createMountain = exports.getMountain = exports.listMountains = exports.seedData = exports.setCustomClaims = exports.onUserCreated = void 0;
var auth_1 = require("./auth");
Object.defineProperty(exports, "onUserCreated", { enumerable: true, get: function () { return auth_1.onUserCreated; } });
Object.defineProperty(exports, "setCustomClaims", { enumerable: true, get: function () { return auth_1.setCustomClaims; } });
var seed_1 = require("./seed");
Object.defineProperty(exports, "seedData", { enumerable: true, get: function () { return seed_1.seedData; } });
var mountains_1 = require("./mountains");
Object.defineProperty(exports, "listMountains", { enumerable: true, get: function () { return mountains_1.listMountains; } });
Object.defineProperty(exports, "getMountain", { enumerable: true, get: function () { return mountains_1.getMountain; } });
Object.defineProperty(exports, "createMountain", { enumerable: true, get: function () { return mountains_1.createMountain; } });
Object.defineProperty(exports, "updateMountain", { enumerable: true, get: function () { return mountains_1.updateMountain; } });
Object.defineProperty(exports, "deleteMountain", { enumerable: true, get: function () { return mountains_1.deleteMountain; } });
var trails_1 = require("./trails");
Object.defineProperty(exports, "listTrails", { enumerable: true, get: function () { return trails_1.listTrails; } });
Object.defineProperty(exports, "getTrail", { enumerable: true, get: function () { return trails_1.getTrail; } });
Object.defineProperty(exports, "createTrail", { enumerable: true, get: function () { return trails_1.createTrail; } });
Object.defineProperty(exports, "updateTrail", { enumerable: true, get: function () { return trails_1.updateTrail; } });
Object.defineProperty(exports, "deleteTrail", { enumerable: true, get: function () { return trails_1.deleteTrail; } });
var posts_1 = require("./posts");
Object.defineProperty(exports, "deletePost", { enumerable: true, get: function () { return posts_1.deletePost; } });
var stats_1 = require("./stats");
Object.defineProperty(exports, "getDashboardStats", { enumerable: true, get: function () { return stats_1.getDashboardStats; } });
//# sourceMappingURL=index.js.map